apiVersion: v1
kind: Service
metadata:
  name: webserver
spec:
  selector:
    app: webserver
    tier: frontend
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 80
    nodePort: 31014
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver
  labels:
    app: webserver
    tier: frontend
spec:
  selector:
    matchLabels:
      app: webserver
      tier: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: webserver
        tier: frontend
    spec:
      containers:
      - name: webapp1
        image: pierrebuniv/webimage
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
